### ISSUE TITLE
Bulk with ObjectSource lead to application crash in 1.2.1.3 and over.

### ISSUE THREAD

**Issue by AlexandreBP** [sksamuel/elastic4s#201]
Hi, 
I am trying to feed an ElasticSearch instance using the bulk operation with ObjectSource:

```
index into ESCatalog doc ObjectSource(look) id look.id
```

Everything works perfectly in elastic4s 1.2.1.2 but I tried to upgrade to 1.3.2 and now it fails with the following error: 

```
! @6jdc46l4a - Internal server error, for (GET) [/elastic_search/import] ->

play.api.Application$$anon$1: Execution exception[[NoClassDefFoundError: com/fasterxml/jackson/module/scala/DefaultScalaModule$]]
    at play.api.Application$class.handleError(Application.scala:296) [play_2.11-2.3.2.jar:2.3.2]
    at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.2.jar:2.3.2]
    at play.api.Application$class.handleError(Application.scala:291) [play_2.11-2.3.2.jar:2.3.2]
    at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.2.jar:2.3.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.2.jar:2.3.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11-2.3.2.jar:2.3.2]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.2.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [scala-library-2.11.2.jar:na]
    at scala.util.Try$.apply(Try.scala:191) [scala-library-2.11.2.jar:na]
    at scala.util.Failure.recover(Try.scala:215) [scala-library-2.11.2.jar:na]
    at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.2.jar:na]
    at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.2.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.2.jar:na]
    at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.11-2.3.2.jar:2.3.2]
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.2.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.2.jar:na]
    at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.2.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.2.jar:na]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [scala-library-2.11.2.jar:na]
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [akka-actor_2.11-2.3.4.jar:na]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [akka-actor_2.11-2.3.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.2.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.2.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.2.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.2.jar:na]
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/module/scala/DefaultScalaModule$
    at models.elastic_search.ESFeeder$$anon$1$$anonfun$1.apply(ESFeeder.scala:41) ~[classes/:na]
    at models.elastic_search.ESFeeder$$anon$1$$anonfun$1.apply(ESFeeder.scala:40) ~[classes/:na]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.2.jar:na]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.2.jar:na]
    at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[scala-library-2.11.2.jar:na]
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1177) ~[scala-library-2.11.2.jar:na]
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[scala-library-2.11.2.jar:na]
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[scala-library-2.11.2.jar:na]
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[scala-library-2.11.2.jar:na]
    at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[scala-library-2.11.2.jar:na]
    at models.elastic_search.ESFeeder$$anon$1.call(ESFeeder.scala:40) ~[classes/:na]
    at models.elastic_search.ESFeeder$$anon$1.call(ESFeeder.scala:35) ~[classes/:na]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_11]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_11]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_11]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_11]
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.module.scala.DefaultScalaModule$
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[na:1.8.0_11]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_11]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_11]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_11]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_11]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_11]
    ... 16 common frames omitted
```

I tried to rollback to 1.2.1.3 but had the same error so I guess that's when the bug was introduced. It seems that the Jackson dependency is missing. I also tried to add the dependency to my sbt file without success. I might be doing something wrong/not compatible with the new code. 
Could you please have a look into this issue or point me in the right direction? 
Thank you very much and btw awesome job guys! :)
