### ISSUE TITLE
Won't work with Play 2.5

### ISSUE THREAD

**Issue by fancellu** [sksamuel/elastic4s#672]
Others have seen this also. I'm using ES 5.x and Play 2.5.10

https://groups.google.com/forum/#!msg/play-framework/c1yh4g-TkTE/TBhq81ZgAQAJ

Is there a known fix for this? Sounds like a major issue, can't believe there aren't more people reporting this issue.

(I know its not your bug, just you might well have some insights in this)

**Comment by sksamuel** [comment]
I've seen it myself with elasticsearch and spark. It's netty to blame for
breaking things between 4.1 and 4.0 imo.

**Comment by fancellu** [comment]
Is there a known fix? I'm not creating an embedded ES, its all standalone, is there a way of talking to ES that doesn't require netty? One that does work with Play 2.5?

**Comment by sksamuel** [comment]
Only http. The tcp client requires netty. Could try forcing 4.0.

**Comment by fancellu** [comment]
Tried
```
   libraryDependencies ++= Seq(
  "com.sksamuel.elastic4s" %% "elastic4s-core" % "5.0.1" excludeAll(
    ExclusionRule(organization = "io.netty")
  ),
  "com.sksamuel.elastic4s" %% "elastic4s-play-json" % "5.0.1"
)
```

it excludes the netty 4.1 stuff, but then dies on run

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/jboss/netty/channel/ReceiveBufferSizePredictorFactory
	at org.elasticsearch.transport.Netty3Plugin.getSettings(Netty3Plugin.java:40)
	at org.elasticsearch.plugins.PluginsService.lambda$getPluginSettings$0(PluginsService.java:85)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.elasticsearch.plugins.PluginsService.getPluginSettings(PluginsService.java:85)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:115)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:228)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:69)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:65)
	at com.sksamuel.elastic4s.ElasticClient$.transport(ElasticClient.scala:101)
	at com.sksamuel.elastic4s.ElasticClient$.transport(ElasticClient.scala:67)
	at inkcache.es.ESPlaypen$.delayedEndpoint$inkcache$es$ESPlaypen$1(ESPlaypen.scala:17)
	at inkcache.es.ESPlaypen$delayedInit$body.apply(ESPlaypen.scala:11)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at inkcache.es.ESPlaypen$.main(ESPlaypen.scala:11)
	at inkcache.es.ESPlaypen.main(ESPlaypen.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: org.jboss.netty.channel.ReceiveBufferSizePredictorFactory
```

**Comment by fancellu** [comment]
BTW, for others with this issue. I used the official Java REST 5.x client

https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_example_requests.html

a bit old school, but works for my needs.

**Comment by sksamuel** [comment]
The rest client is the future but right now it's not much more than a
wrapper around the apache http client.

**Comment by fancellu** [comment]
yes, I noticed that, but at least it doesn't go bang.

https://gist.github.com/fancellu/4d0a1ee134b6a4f37f90f6e5e851b588

**Comment by sksamuel** [comment]
Yes. Hopefully play will update soon. And spark too.
