### ISSUE TITLE
Error after upgrading to 5.4.0

### ISSUE THREAD

**Issue by animageofmine** [sksamuel/elastic4s#905]
All was well until 5.3.2, but now we get the following error:

```
[info] Compiling 37 Scala sources and 1 Java source to /home/ae/workspace/target/scala-2.11/classes...
[warn] Class com.carrotsearch.hppc.cursors.ObjectObjectCursor not found - continuing with a stub.
[warn] Class com.carrotsearch.hppc.cursors.ObjectObjectCursor not found - continuing with a stub.
[warn] Class com.carrotsearch.hppc.ObjectLookupContainer not found - continuing with a stub.
[warn] Class com.carrotsearch.hppc.ObjectLookupContainer not found - continuing with a stub.
[warn] Class com.carrotsearch.hppc.ObjectContainer not found - continuing with a stub.
[warn] Class com.carrotsearch.hppc.ObjectContainer not found - continuing with a stub.
[warn] Class com.carrotsearch.hppc.ObjectObjectMap not found - continuing with a stub.
[warn] Class com.carrotsearch.hppc.ObjectObjectMap not found - continuing with a stub.
[warn] Class com.carrotsearch.hppc.ObjectObjectHashMap not found - continuing with a stub.
[warn] Class com.carrotsearch.hppc.ObjectObjectHashMap not found - continuing with a stub.
[error] Class com.carrotsearch.hppc.ObjectLookupContainer not found - continuing with a stub.
[warn] 10 warnings found
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```
Any idea what could be missing here? 

We are using play framework and scala 2.11.8. Let me know if you need more info.

**Comment by animageofmine** [comment]
I guess, I didn't see any issues after upgrading to 5.4.1. Probably lucene version was the issue?

**Comment by sksamuel** [comment]
It's because elasticsearch added it to the build, but set it to ruintime only, so it needed to be added to our build - hence 5.4.1.

**Comment by animageofmine** [comment]
Great, thanks so much Stephen!
