### ISSUE TITLE
Change log for v 6.0? many breaking changes. 

### ISSUE THREAD

**Issue by jeremiahlukus** [sksamuel/elastic4s#1569]
After updating to 6.4.0 from 6.2.6 there were many breaking changes with no change log this is pretty hard to fix. 

A few things that have been removed 
`import com.sksamuel.elastic4s.searches.MultiSearchDefinition`
 `import com.sksamuel.elastic4s.searches.SearchDefinition`
` import com.sksamuel.elastic4s.searches.queries.QueryDefinition`
`import com.sksamuel.elastic4s.cluster.ClusterHealthDefinition`
` value execute is not a member of com.sksamuel.elastic4s.http.HttpClient`
`not found: value HttpClient`
`value publisher is not a member of com.sksamuel.elastic4s.http.HttpClient`
`import com.sksamuel.elastic4s.searches.aggs.AggregationDefinition`
`import com.sksamuel.elastic4s.searches.queries.BoolQueryDefinition`
`import com.sksamuel.elastic4s.searches.sort.SortDefinition`
` QueryStringQueryDefinition`

and a few more.

**Comment by sksamuel** [comment]
They're called ***Request rather than **Definition.

There were no changes if you go via the elastic dsl, which has always been the way to do it, rather than making the classes yourself.

HttpClient is now ElasticClient so that's a breaking change.

**Comment by sksamuel** [comment]
Any more questions just add them here.

**Comment by chenrui333** [comment]
For people coming into this issue, here are the change we made:

- `s/SearchDefinition/SearchRequest/g`
- `s/QueryDefinition/Query/g`
- `s/SortDefinition/Sort/g`

The `s/HttpClient/ElasticClient/g` change would involve with some type fixes depending on your usage.
